### ISSUE TITLE
where is the test code  i train the model but can not test on test dataset

### ISSUE THREAD

**Issue by senlin-ali** [demonzyj56/E3Outlier#1]
where is the test code  i train the model but can not test on test dataset thanks

**Comment by demonzyj56** [comment]
@1senlin The proposed E3Outlier is an unsupervised outlier detection method which deals with unlabelled data mixed with outliers.  There does not exist a separate training dataset apart from the target unlabelled dataset itself.  Please refer to our paper for more information.
